### ISSUE TITLE
Opening the app creates a new Sim Card Contact

### ISSUE THREAD

**Issue by CL33F** [yeriomin/DumbphoneAssistant#1]
Upon opening the app a new contact is created on the Sim Card "abcdefghijklmnopqr" "24448888888"

Attempting to delete the record results in the error: "Could not remove contact from SIM"

Each subsequent opening of the application results in a duplicate contact being created.

Android version: 5.1.1
Android model: MotoG3

**Comment by ghost** [comment]
I can confirm, same issue on my OnePlus X - Android 5.1.1

**Comment by yeriomin** [comment]
Hi again. I'm starting to think f-droid user base is not that big ;) Thanks a lot for creating issues.
Fixed. Should be in f-droid's repo in a day or two.
24448888888is a dummy contact used to test the character limit for the sim card (which is different from sim to sim). With delete function broken this contact was remaining after each launch.

**Comment by CL33F** [comment]
No problem man. Thanks for all your hard work in creating this.
I'll update when it's next available and let you know if I find any further issues.
