### ISSUE TITLE
Read-only on SIM in color

### ISSUE THREAD

**Issue by PanderMusubi** [yeriomin/DumbphoneAssistant#10]
Please show read-only contacts on SIM, that cannot be deleted from SIM, in a different color such as blue.

**Comment by yeriomin** [comment]
Unfortunately, Android does not provide a way to know if the SIM contact is read-only. Frankly, I have never seen a read-only contact on a SIM, so I wouldn't be able to test it even if the docs had that info.

Won't fix.

**Comment by PanderMusubi** [comment]
These are numbers for voicemail (domestic and international). Could not delete these individually but strangely could delete then with bulk delete.
