### ISSUE TITLE
Remove unsupported diacritics

### ISSUE THREAD

**Issue by PanderMusubi** [yeriomin/DumbphoneAssistant#12]
Some diacritics are not supported and those contacts cannot be copied. They should be copied with only removing the unsupported diacritics (and keeping the supported diacritics). For sure a list or function is available to inquire which are and aren't supported and how to remove unsupported diacritics.

One example is that a name with a 'ž' is not supported. There a 'z' should be used.

**Comment by yeriomin** [comment]
This is implemented already.  Turn on transliteration through the main menu.
