### ISSUE TITLE
Copy All not working since Marshmallow upgrade

### ISSUE THREAD

**Issue by slipslider** [yeriomin/DumbphoneAssistant#14]
Copy All button does nothing since upgrading to Marshmallow.
Also, copying them individually, my last contact (alphabetically) 'Fails' to copy.
Sony Xperia Z3 Compact.

**Comment by yeriomin** [comment]
To clarify: "Copy All to SIM"?
Also, keep in mind that android does not tell apps when the SIM card is full, no way to get total capacity either. SIM cards can hold 100-200 contacts. If most of your contacts are copied and the rest (after 170 for example) are not, that means that the sim card is full.
I'll look into the copy all issue. Thanks for your feedback.

**Comment by slipslider** [comment]
Thanks for the info Yeriomin.  
To clarify my issue.
Less than 100 contacts to a SIM with plenty of space.
But the "Copy All to SIM" button at the top of the contacts list does not work, nor does the button beside the last contact at the bottom of the list.
