### ISSUE TITLE
List sizes

### ISSUE THREAD

**Issue by PanderMusubi** [yeriomin/DumbphoneAssistant#8]
For address book, list total number of name-number entries. For SIM, list total capacity and number of used entries.

**Comment by yeriomin** [comment]
Android does not provide a way to get SIM total capacity, unfortunately. The only way to get it would be to insert contacts until SIM says no, and then delete them. Which is a long and **unsafe** operation. For that reason used numbers count for both SIM and phone are a bit useless.

I will consider adding this as an option.

**Comment by PanderMusubi** [comment]
instead of showing x (contacts) out of y (maximum contacts), only show x
