### ISSUE TITLE
Show only unique name-number pairs for address book

### ISSUE THREAD

**Issue by PanderMusubi** [yeriomin/DumbphoneAssistant#9]
Please, show only unique name-number pairs for address book. Probably because duplication in asdressbook for generated contacts for WhatsApp and Telegram, many duplicate name-number entries are show.

**Comment by yeriomin** [comment]
Most users will expect to see _contacts_, not  name-number pairs, so inventing something else than contacts will be confusing. Besides that, your other issue (#11) deals with the same problem.

**Comment by PanderMusubi** [comment]
I understand, it also depends on the options used to create the name and that it is truncated makes it very difficult to match.

**Comment by PanderMusubi** [comment]
Sorry, my comment was on matching phone contacts and sim contacts. I see a lot of duplicates and triplicates on the phone side because of whatsapp and telegram
